export const dataFetch = {
  data: [
    {
      id: "1",
      name: "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
      price: "317.00",
      user: "Жанна Маслова",
      createdAt: "2024-04-22T20:31:16.550Z",
      statusName: "зеленый",
      statusColor: "лиловый",
    },
    {
      id: "2",
      name: "The Football Is Good For Training And Recreational Purposes",
      price: "954.00",
      user: "Анна Журавлева",
      createdAt: "2024-01-24T06:06:18.049Z",
      statusName: "Псебай",
      statusColor: "оливковый",
    },
    {
      id: "3",
      name: "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
      price: "586.00",
      user: "Ия Евдокимова",
      createdAt: "2024-04-17T23:28:07.837Z",
      statusName: "ПО",
      statusColor: "орхидный",
    },
    {
      id: "4",
      name: "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
      price: "626.00",
      user: "Модест Ермаков",
      createdAt: "2023-12-19T18:19:02.475Z",
      statusName: "оптимизационный",
      statusColor: "красный",
    },
    {
      id: "5",
      name: "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
      price: "873.00",
      user: "Пелагея Рожкова",
      createdAt: "2024-04-10T14:15:31.711Z",
      statusName: "игры",
      statusColor: "голубой",
    },
    {
      id: "6",
      name: "The Football Is Good For Training And Recreational Purposes",
      price: "598.00",
      user: "Захар Федотов",
      createdAt: "2023-07-29T02:01:18.848Z",
      statusName: "strictly",
      statusColor: "бирюзовый",
    },
  ],
};
